### ISSUE TITLE
About AOP implementation, such as @Retryable

### ISSUE THREAD

**Issue by happyxiaofan** [spring-projects/spring-retry#87]
AspectJ (for post complier weave) or CGLIB(dynamic weave)

**Comment by dsyer** [comment]
Is that a question? Feature request? Not sure how to respond since we already use AOP for `@Retryable`.

**Comment by dtitov** [comment]
Sorry, that might be off-topic here, but I didn't want to create an issue for this question.

I'm using spring-retry for retrying in Spring Cloud Config. So I have something like:
```yaml
spring:
    application:
        name: ***
    cloud:
        config:
            ...
            failFast: true
            retry:
                max-attempts: 100
                max-interval: 100000
```

That works like a charm, **but** only as long as I have `spring-boot-starter-aop` on the application's classpath. If I remove AOP-dependency, retry functionality is working no more. My question is: why AOP dependency is not included to Spring Retry, so it can transitively and transparently come to my application without a need to declare it explicitly?
